config/routes.rb
Rails.application.routes.draw do

  root to: 'venues#index'

    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :venues, only: [:index, :show] do
    resources :bookings, only: [:new, :create, :update, :edit, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :venue
  belongs_to :user

  validate :booking_date_time, :booking_cannot_be_on_top_of_another

  def booking_date_time
    if to <= from
      errors.add(:to, "The booking to should be after from")
    end
  end

  def booking_cannot_be_on_top_of_another
    # find bookings of same venue
    # end date in between current booking interval
    # start date in between current booking interval
    # start is before start, end is after end
    conflicting_bookings = Booking.where("venue_id = :venue_id and ((\"from\" >= :from and \"from\" < :to) or (\"to\" > :from and \"to\" <= :to) or (\"from\" <= :from and \"to\" >= :to))", 
    {venue_id: venue.id, from: from, to: to})
    logger.error(conflicting_bookings.length)
    conflicting_bookings.each do |b|
      logger.error(b)
    end
    if conflicting_bookings.length > 0
      errors.add(:from, "The booking timing conflicts with an existing booking")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :bookings
end

app/controllers/application_controller.rb
include SessionsHelper
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :logged_in_user

  def new
    @venue = Venue.find(params[:venue_id])
  end

  def create
    @venue = Venue.find(params[:venue_id])
    @booking = @venue.bookings.new(booking_params)
    user = current_user
    @booking.user = user
    @booking.save
    redirect_to venue_path(@venue)
  end

  def edit
  end

  def update
  end

  def destroy
      @venue = Venue.find(params[:venue_id])
    @booking = Booking.find(params[:id])

    if @booking.user != current_user
      flash[:danger] = "You do not own this booking."
      else
    @booking.destroy
      end

      redirect_to venue_path(@venue)
  end

  private
    def booking_params
      params.require(:booking).permit(:from, :to)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username].downcase)
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to venues_url
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to login_url
    end
  end

  def destroy
    log_out
    redirect_to venues_url
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :logged_in_user

  def index
    @venues = Venue.all
  end

  def show
    @venue = Venue.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id
    end

    def log_out
      session.delete(:user_id)
      @current_user = nil
    end

    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end

    def logged_in?
      !current_user.nil?
    end

    def logged_in_user
        unless logged_in?
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= form_with(model: [ @venue, @venue.bookings.build ], local: true) do |form| %>
<p>Venue to book: <%= @venue.name %></p>
    <%= label_tag(:from, "From:") %>
    <%= datetime_local_field(:booking, :from) %>
    <%= label_tag(:from, "To:") %>
    <%= datetime_local_field(:booking, :to) %>
    <%= submit_tag("Book") %>
  <% end %>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <style>
    body {
  padding-top: 5rem;
}
.starter-template {
  padding: 3rem 1.5rem;
}


    </style>
  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="<%= venues_path %>">Booking System</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample06" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample06">
    <ul class="navbar-nav mr-auto">
    </ul>
    
    <form class="form-inline my-2 my-md-0">
    <% if logged_in? %>

    <ul class="navbar-nav mr-auto">
    <li class="nav-item">

    <a class="nav-link" href="#">Logged in as: <%= current_user.username %></a>
    
      </li> 
      <li class="nav-item">
      <a class="nav-link" href="<%= logout_path %>">Log out</a>
        </li> 
    </ul>

    <% else %>

      <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <a class="nav-link" href="<%= login_path %>">Log in</a>
        </li> 
      </ul>

    <% end %>
    </form>
  </div>
</nav>

<main role="main" class="container">

  <div class="starter-template">

<% flash.each do |name, msg| -%>

<div class="alert alert-<%= name %>" role="alert">
  <%= msg %>
</div>

<% end -%>
 
  <%= yield %>   

  </div>

</main>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<script>

$(function() {
  $('input[type="datetime-local"]').daterangepicker({
    singleDatePicker: true,
    timePicker: true,
    showDropdowns: true,
    timePickerIncrement: 60,
    locale: {
      format: 'YYYY/MM/DD hh:mm A'
    }
  });
});
</script>
  </body>
</html>

app/views/venues/index.html.erb
<h1>Venues</h1>
<div class="container">
  <div class="row">
<% @venues.each do |venue| %>
    <div class="col-sm-4">
  <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= venue.name %></h5>
    <a href="<%= venue_path(venue.id) %>" class="btn btn-primary">Details</a>
  </div>
</div>
    </div>
<% end %>
  </div>
</div>

app/views/venues/show.html.erb
<h1><%= @venue.name %><br></h1>
<h2>Bookings</h2>
<table class="table">
  <thead>
    <tr>
      <th scope="col">From</th>
      <th scope="col">To</th>
      <th scope="col">Booked By</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
<% @venue.bookings.each do |booking| %>
    <tr>
      <td><%= booking.from %></td>
      <td><%= booking.to %></td>
      <td><%= booking.user.username %></td>
      <td>
    <% if booking.user == current_user %>
    <%= link_to "Cancel", venue_booking_path(@venue, booking), method: :delete, :confirm => "Are you sure you want to delete this booking?" %>
      <% end %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
<a href="<%= new_venue_booking_path(@venue.id) %>">
<button type="button" class="btn btn-primary">Book this venue</button>
</a>
</p>

<p>
<a href="<%= venues_path %>">
<button type="button" class="btn btn-primary">Other venues</button>
</a>
</p>